### ISSUE TITLE
Gantt not rendering / showing

### ISSUE THREAD

**Issue by abrannokia** [zodman/django-frappe-gantt#2]
Hi,

Could you please help me?

The app works, but the gantt is not showing...

Thanks,

Alex

**Comment by abrannokia** [comment]
![image](https://user-images.githubusercontent.com/47685040/66189572-b3f06280-e692-11e9-8fc6-918bc2bfedaf.png)

**Comment by abrannokia** [comment]
require() function giving ReferenceError: require is not defined

**Comment by zodman** [comment]
you need compile it.

```
yarn install
yarn run dev
```

**Comment by abrannokia** [comment]
Thanks a lot !

Alex
